"""device fingerprint on sessions

Revision ID: 13105901c60d
Revises: 5f043cab302f
Create Date: 2026-08-08 14:04:15.032805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13105901c60d'
down_revision: Union[str, Sequence[str], None] = '5f043cab302f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('device_fingerprint', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_sessions_device_fingerprint'), 'sessions', ['device_fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_device_fingerprint'), table_name='sessions')
    op.drop_column('sessions', 'device_fingerprint')
    # ### end Alembic commands ###
