"""idempotency key on stored files

Revision ID: 4c6d246c56dd
Revises: 13105901c60d
Create Date: 2026-08-08 14:08:56.018217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c6d246c56dd'
down_revision: Union[str, Sequence[str], None] = '13105901c60d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stored_files', sa.Column('idempotency_key', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_stored_files_idempotency_key'), 'stored_files', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_stored_files_sha256'), 'stored_files', ['sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stored_files_sha256'), table_name='stored_files')
    op.drop_index(op.f('ix_stored_files_idempotency_key'), table_name='stored_files')
    op.drop_column('stored_files', 'idempotency_key')
    # ### end Alembic commands ###
