"""audit_hash_chain

Revision ID: 7d67f9f47d4b
Revises: 6fe68b628175
Create Date: 2026-08-08 11:28:17.486721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d67f9f47d4b'
down_revision: Union[str, Sequence[str], None] = '6fe68b628175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('prev_hash', sa.String(length=64), server_default='0000000000000000000000000000000000000000000000000000000000000000', nullable=False))
    op.add_column('audit_logs', sa.Column('entry_hash', sa.String(length=64), server_default='0000000000000000000000000000000000000000000000000000000000000000', nullable=False))
    op.create_index(op.f('ix_audit_logs_entry_hash'), 'audit_logs', ['entry_hash'], unique=False)
    # ### end Alembic commands ###

    _backfill_chain(op.get_bind())


def _backfill_chain(bind) -> None:
    """
    Hash-chain every pre-existing entry so the
    tamper-evidence property holds from the very
    first row. Ordering must match the verification
    replay (created_at asc, id asc).
    """

    import hashlib

    from sqlalchemy import text

    rows = bind.execute(
        text(
            "SELECT id, created_at, user_id, action, "
            "details, resource_type, resource_id "
            "FROM audit_logs "
            "ORDER BY created_at ASC, id ASC"
        )
    ).fetchall()

    prev_hash = "0" * 64

    for row in rows:

        created_at = row.created_at

        if created_at.tzinfo is None:
            created_at = created_at.replace(
                tzinfo=__import__(
                    "datetime"
                ).timezone.utc
            )

        canonical = "|".join(
            [
                prev_hash,
                created_at.isoformat(),
                str(row.user_id) if row.user_id else "",
                row.action,
                row.details or "",
                row.resource_type or "",
                row.resource_id or "",
            ]
        )

        entry_hash = hashlib.sha256(
            canonical.encode("utf-8")
        ).hexdigest()

        bind.execute(
            text(
                "UPDATE audit_logs SET "
                "prev_hash = :prev, entry_hash = :entry "
                "WHERE id = :id"
            ),
            {
                "prev": prev_hash,
                "entry": entry_hash,
                "id": row.id,
            },
        )

        prev_hash = entry_hash


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_entry_hash'), table_name='audit_logs')
    op.drop_column('audit_logs', 'entry_hash')
    op.drop_column('audit_logs', 'prev_hash')
    # ### end Alembic commands ###
